---

- hosts: admin
  become: yes
  vars_files:
    - vars/all.yml
    - vars/all-dev.yml
  roles:
    - admin

- hosts: blog
  become: yes
  vars_files:
    - vars/all.yml
    - vars/all-dev.yml
  roles:
    - blog

- hosts: redis
  become: yes
  vars_files:
    - vars/all.yml
    - vars/all-dev.yml
  roles:
    - redis

- hosts: proxy
  become: yes
  vars_files:
    - vars/all.yml
    - vars/all-dev.yml
  roles:
    - proxy

- hosts: monitor
  become: yes
  vars_files:
    - vars/all.yml
    - vars/all-dev.yml
  roles:
    - monitor