---

- hosts: localhost
  connection: local
  vars_files:
    - vars/all.yml
  roles:
    - aws_keypair
    - aws_creation

- hosts: redis
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - redis

- hosts: admin
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - admin

- hosts: blog
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - blog

- hosts: proxy
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - proxy

- hosts: monitor
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - monitor