# Install apache modules task
---

- name: Install Apache Modules
  apache2_module:
    state: present
    name: "{{ item }}"
  notify: restart apache
  with_items:
    - rewrite
    - proxy
    - proxy_http