# install zabbix-agent task
---

- name: "Ubuntu | Installing deb repository Ubuntu"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/2.4/ubuntu/ trusty main"
    state: present
  become: yes

- name: "Ubuntu | Installing deb-src repository Ubuntu"
  apt_repository:
    repo: "deb-src http://repo.zabbix.com/zabbix/2.4/ubuntu/ trusty main"
    state: present
  become: yes

- name: "Ubuntu | Install gpg key"
  apt_key:
    id: 79EA5ED4
    url: "http://repo.zabbix.com/zabbix-official-repo.key"
  become: yes

- name: "Ubuntu | Installing zabbix-agent"
  apt:
    pkg: zabbix-agent
    state: present
    update_cache: yes
    cache_valid_time: 0
  become: yes

- name: "Ubuntu | Enable the service"
  service:
    name: zabbix-agent
    enabled: yes
  become: yes