# Elastic IPs creation task
---

# Create EIP for instances
- name: EIP for proxy
  ec2_eip:
    device_id: "{{ proxy_instance.instances[0].id }}"
  register: proxy_ip

- name: EIP for admin app
  ec2_eip:
    device_id: "{{ admin_instance.instances[0].id }}"
  register: admin_ip

- name: EIP for blog app
  ec2_eip:
    device_id: "{{ blog_instance.instances[0].id }}"
  register: blog_ip

- name: EIP for monitor
  ec2_eip:
    device_id: "{{ monitor_instance.instances[0].id }}"
  register: monitor_ip

- name: EIP for redis
  ec2_eip:
    device_id: "{{ redis_instance.instances[0].id }}"
  register: redis_ip

# Add instances to groups
- add_host:
    name: "{{ proxy_ip.public_ip }}"
    groups: proxy,zabbix-agent

- add_host:
    name: "{{ redis_ip.public_ip }}"
    groups: redis,zabbix-agent

- add_host:
    name: "{{ admin_ip.public_ip }}"
    groups: admin,zabbix-agent

- add_host:
    name: "{{ blog_ip.public_ip }}"
    groups: blog,zabbix-agent

- add_host:
    name: "{{ monitor_ip.public_ip }}"
    groups: monitor