---

# Create host groups
- add_host:
    name: 52.52.37.253
    groups: proxy

#- add_host:
#    name: 52.52.48.46
#    group: redis
#
#- add_host:
#    name: "{{ admin_ip.public_ip }}"
#    group: admin
#
#- add_host:
#    name: 52.52.46.215
#    groups: blog
#
#- add_host:
#    name: 52.52.47.86
#    groups: monitor