# Configure apache task
---

- name: "Ubuntu | install apache vhost"
  template:
    src: "apache_vhost.conf.j2"
    dest: "/etc/apache2/conf-available/zabbix.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: "Install Ansible module dependencies"
  apt:
    name: python-psycopg2
    state: present