# Task for zabbix-server configure
---

- name: "Configure zabbix-server"
  template: src=zabbix_server.conf.j2
            dest=/etc/zabbix/zabbix_server.conf
            owner=zabbix
            group=zabbix
            mode=0644
  notify: zabbix-server restarted

- name: "Create include dir zabbix-server"
  file:
    path: /etc/zabbix/zabbix_server.conf.d
    owner: zabbix
    group: zabbix
    state: directory

- name: "Configure zabbix-web"
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: zabbix
    group: zabbix
    mode: 0644