---

- name: get current user name
  delegate_to: localhost
  command: whoami
  register: current_user

- stat: path="{{ public_key_path }}"
  register: keyfile

- name: generate ssh keys
  command: ssh-keygen -N '' -f "{{ private_key_path }}"
  when: not keyfile.stat.exists

- name: import key
  ec2_key:
    name: "{{ ec2_config.keypair }}"
    key_material: "{{ item }}"
  with_file: "{{ public_key_path }}"
  register: keypair