---
#    - name: get current user name
#      delegate_to: localhost
#      command: whoami
#      register: current_user

- stat: path="~/.ssh/{{ ec2_config.keypair }}.pub"
  register: keyfile

- name: generate ssh keys
  command: ssh-keygen -N '' -f ~/.ssh/"{{ ec2_config.keypair }}"
  when: not keyfile.stat.exists

- name: import key
  ec2_key:
    name: "{{ ec2_config.keypair }}"
    key_material: "{{ item }}"
  with_file: "~/.ssh/{{ ec2_config.keypair }}.pub"
  register: keypair